# Generated by Django 2.0 on 2020-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0003_profile_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
