# Generated by Django 2.0 on 2020-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0004_auto_20200303_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('due', models.DateField(blank=True, null=True)),
                ('assigned', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
