# Generated by Django 2.0 on 2020-03-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0005_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
