# Generated by Django 3.0.4 on 2020-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20200321_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='assigned',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cards',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
