# Generated by Django 3.0.4 on 2020-03-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20200321_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='id',
        ),
        migrations.AddField(
            model_name='cards',
            name='c_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
