# Generated by Django 3.0.4 on 2020-04-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_chat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
