# Generated by Django 3.0.4 on 2020-04-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_cards_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cards',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
