# Generated by Django 3.0.6 on 2020-05-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20200401_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
